<?php
	define('PROJECT_NAME',"ebayapiservices");
	define('SELLER_PROFILES_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/analytics/get-all-seller-profiles.php");
	define('SELLER_DASHBOARD_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/trading/get-seller-dashboard.php");
	define('RECOMMENDATION_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/listing-recommendation/get-recommendations-summary.php");
	define('RECOMMENDATION_TYPE_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/listing-recommendation/get-recommendations-by-type.php");
	define('RECOMMENDATION_ITEM_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/listing-recommendation/get-recommendations-by-itemid.php");
	define('VIOLATION_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/compliance/get-listing-violations-summary.php");
	define('VIOLATION_TYPE_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/compliance/get-listing-violations.php");
	define('USER_PROFILE_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/shopping/get-user-profile.php");
?>