<?php
	define('BASE_URL','http://'.$_SERVER['HTTP_HOST'].'/EbayData/');
	define('PROJECT_NAME',"ebayapiservices");
	define('SELLER_PROFILES_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/analytics/get-all-seller-profiles.php");
	define('SELLER_DASHBOARD_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/trading/get-seller-dashboard.php");
	define('RECOMMENDATION_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/listing-recommendation/get-recommendations-summary.php");
	define('RECOMMENDATION_TYPE_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/listing-recommendation/get-recommendations-by-type.php");
	define('RECOMMENDATION_ITEM_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/listing-recommendation/get-recommendations-by-itemid.php");
	define('VIOLATION_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/compliance/get-listing-violations-summary.php");
	define('VIOLATION_TYPE_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/compliance/get-listing-violations.php");
	define('USER_PROFILE_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/shopping/get-user-profile.php");
	define('TRAFFIC_REPORT',"https://showcase.247cloudhub.co.uk/ebayapis/analytics/get_traffic_report.php");
	define('LISTING_RECOMMENDATIONS_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/listing-recommendation/listing-recommendation.php");
	define('CATEGORY_ASPECTS_API_URL',"https://showcase.247cloudhub.co.uk/ebayapis/taxonomy/get-item-aspects-category_noformat.php");
	define('ITEM_SKU_CLODHUB_API_URL','http://compete.247commerce.com/InventoryAPI/Api/eBay/GetEbayItemIdAndCategoryDetails');
	define('GET_CAMPAIGN_API_URL','https://showcase.247cloudhub.co.uk/ebayapis/campaign/get_campaign.php');
	define('CREATE_CAMPAIGN_API_URL','https://showcase.247cloudhub.co.uk/ebayapis/campaign/create_campaign.php');
	define('UPDATE_CAMPAIGN_API_URL','https://showcase.247cloudhub.co.uk/ebayapis/campaign/update_campaign.php');
	define('RESUME_CAMPAIGN_API_URL','https://showcase.247cloudhub.co.uk/ebayapis/campaign/resume_campaign.php');
	define('PAUSE_CAMPAIGN_API_URL','https://showcase.247cloudhub.co.uk/ebayapis/campaign/pause_campaign.php');
	define('END_CAMPAIGN_API_URL','https://showcase.247cloudhub.co.uk/ebayapis/campaign/end_campaign.php');
	define('GET_SESSION_STATUS_API_URL','http://configure.247commerce.com/UserApis/api/UserSettings/GetSessionStatus/');
?>